title: "FOSS Soft Robotics"
description: "Free & open resources for soft robotics."
theme: minima

# Custom domain setup (apex)
url: "https://soft-robotics.com"
baseurl: ""   # empty for apex domain

# Show these as top navigation tabs (files must be in /docs)
header_pages:
  - about.md
  - projects.md
  - research.md
  - blog.md
  - media.md
  - contact.md

markdown: kramdown
kramdown:
  input: GFM

