title: "FOSS Soft Robotics"
description: "Free & open resources for soft robotics."
theme: minima
# Important for project sites:
url: "https://anatol-gogoj.github.io"
baseurl: "/FOSS_Soft_Robotics"

# Show these as top navigation tabs:
header_pages:
  - about.md
  - projects.md
  - research.md
  - blog.md
  - media.md
  - contact.md

markdown: kramdown
kramdown:
  input: GFM
