name: CI
on:
  push:
    branches: [ main, V0.2-Content ]
  pull_request:
    branches: [ main, V0.2-Content ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files
        run: ls -la
